### ISSUE TITLE
virus detected when trying to download

### ISSUE THREAD

**Issue by gibabuscape** [switchabl/t19xx_usb#1]
When trying to download the file, WIndows Defender is detecting viruses in the .exe. Do not let it download at all.

**Comment by gibabuscape** [comment]
![image](https://user-images.githubusercontent.com/132455145/235930713-62412adf-6755-40f9-b06b-67c136cee31f.png)

**Comment by WouterJD** [comment]
Hi since this .exe is 3 years old it MAY be a false positive, caused by the fact that the software is an installer.
But this is no guarantee, I hope @switchabl can give a response to this, but did not see him online for a while.

**Comment by gibabuscape** [comment]
Ok
